DROP DATABASE IF EXISTS notable;
CREATE DATABASE notable;
\c notable;

drop table if exists users cascade;
create table if not exists users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username varchar(40),
  user_email varchar(140)
)