DROP DATABASE IF EXISTS notable;
CREATE DATABASE notable;
\c notable;

drop table if exists doctors cascade;
create table if not exists doctors (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name varchar(40),
  last_name varchar(140)
)

drop table if exists appointment cascade;
create table if not exists appointment (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  doctor_id integer references doctors(id),
  patient_first_name varchar(40),
  patient_last_name varchar(40),
  date_time varchar(40),
  kind boolean not null
)


-- insert into "doctors" (id, first_name, last_name) values (1, 'hibbert', 'julius')
-- insert into "doctors" (id, first_name, last_name) values (2, 'krieger', 'algernop')
-- insert into "doctors" (id, first_name, last_name) values (3, 'riviera', 'nick')
-- new patient is false
-- old patient is true
-- insert into "appointment" (id, doctor_id, patient_first_name, patient_last_name, date_time, kind) values (1, 2, 'sterling', 'archer', '8:00AM', false);
-- insert into "appointment" (id, patient_first_name, patient_last_name, date_time, kind) values (2, 'cyril', 'figis', '8:30AM', true);


